### ISSUE TITLE
Unable to load into site

### ISSUE THREAD

**Issue by flumeeee** [HannahGuo/RankedRecords#29]
Getting this error:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command

any advice?

**Comment by tinchs** [comment]
Hi, I'm also getting that error message :/

**Comment by HannahGuo** [comment]
Hey! I've _finally_ gotten around to getting the site back up (on a different hosting platform, Render). 

It also underwent a complete rewrite, and I'm just doing some final fix ups and bug tests. But the beta and final site will be at this URL: https://ranked-records.onrender.com/

Cheers!

**Comment by tinchs** [comment]
Thank you very much!
